Point_Sale/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("StartUp_Page.urls")),
   
]

StartUp_Page/urls.py
from django.urls import path

from . import views

app_name = "StartUp_Page1"
urlpatterns = [
    path("", views.display, name = "display_page"),
    path("Login", views.signIn, name = "login"),
    path("signUp", views.signUp, name = "sgnUp"),
    path("home", views.homePage, name = "homeP"),
    path("product", views.product, name = "Product"),
    path("product/delete/<int:pk>", views.prodDelete, name = "DeleteP"),
    path("orders", views.orders, name = "Orders"),
    path("profile", views.profile, name = "Profile"),
    path("staff", views.staff, name = "Staff"),
    path("logout", views.logoutFun, name = "logout1"),
]

StartUp_Page/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
CATEGORY = (
    ('Stationary', 'Stationary'),
    ('Electronics', 'Electronics'),
    ('Food', 'Food'),
)


class Product(models.Model):
    name = models.CharField(max_length=100, null=True)
    quantity = models.PositiveIntegerField(null=True)
    category = models.CharField(max_length=50, choices=CATEGORY, null=True)

    def __str__(self):
        return f'{self.name}'


class Order(models.Model):
    name = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    customer = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    order_quantity = models.PositiveIntegerField(null=True)

    def __str__(self):
        return f'{self.customer}-{self.name}'


StartUp_Page/views.py
from django.shortcuts import render, redirect
from django import forms
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import Product


# Create your views here.
# class for Login
class NewForm_forSignIn(forms.Form):
    username = forms.CharField(label= "Username", required = True)
    password = forms.CharField(label= "Password", required = True)


class productForm(forms.Form):

    product = forms.CharField(label= "product", required = True)
    quantity = forms.IntegerField(label= "quantity", required = True)
    category = forms.CharField(label= "category", required = True)


# class for Sign up
class NewForm_forSignUp(forms.Form):
    username = forms.CharField(label= "Username", required = True)
    password = forms.CharField(label= "Password", required = True)
    confirmPass = forms.CharField(label= "Confirm Password", required = True)
   


def display(request):
    return render(request, "StartUp_Page/startPage.html");

@login_required(login_url = 'StartUp_Page1:login')
def homePage(request):
    return render(request, "Interfaces/index.html")

def product(request):
    if request.method == 'POST':
        form = productForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("{% url 'StartUp_Page1:Product' %}")
    else:
        form = productForm()
    items = Product.objects.all()
    contex = {
        'items': items,
        'form':  form
    }
    return render(request, "Interfaces/product.html", contex)

def prodDelete(request, pk):
    item = Product.objects.get(id = pk)
    if request.method == 'POST':
        item.delete()
        redirect('StartUp_Page1:Product')
    return render(request, "Interfaces/products_delete.html")


def staff(request):
    return render(request, "Interfaces/staff.html", {
        "name": "name is bilal"
    })


def orders(request):
    return render(request, "Interfaces/order.html", {
        "name": "name is bilal"
    })


def profile(request):
    return render(request, "Interfaces/profile.html", {
        "name": "name is bilal"
    })


def signIn(request):
    if request.method == "POST":
        usname = request.POST.get("username")
        pswrd = request.POST.get("password")

        user = authenticate(request, username = usname, password = pswrd)
        if user is not None:
            login(request, user)
            return redirect('StartUp_Page1:homeP')


        #form = NewForm_forSignIn(request.POST)
        #if form.is_valid:
        #   usname = form["username"]
        #    paswrd = form["password"]


    return render(request, "StartUp_Page/SigninPage.html", {
        "form": NewForm_forSignIn()
    });


def signUp(request):
    if request.method == "POST":
        usname = request.POST.get("Username")
        paswrd = request.POST.get("Password")
        confimPass = request.POST.get("confirmPassword")

        if confimPass != paswrd:
            return HttpResponse("Invalid Password not same")

        else:
            usr = User.objects.create_user(usname, paswrd, confimPass)
            usr.save()

            return redirect("StartUp_Page1:login")

            
    return render(request, "StartUp_Page/signUpPage.html");




def logoutFun(request):
    logout(request)
    return redirect('StartUp_Page1:login')

StartUp_Page/templates/Interfaces/decorator.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>

<body style="background: rgb(83, 80, 80)">

</body>
<div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">
    <h1 style="color: rgb(255, 255, 255);">
        Sorry...... You are not authorized
        to acess this page</h1>
    <p> <a href="{% url 'dashboard-index' %}">Click Here To Go Back</a> </p>
</div>

</html>

StartUp_Page/templates/Interfaces/index.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!--FontAwesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"
        integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">

    <!--Chartjs CDN-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>

    <!--Custome CSS-->
    <link rel="stylesheet" href="./style.css">

    <title>Home Page</title>
</head>

<body>

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-info bg-info">
        <div class="container">
            <a class="navbar-brand text-white" href="{% url 'StartUp_Page1:homeP' %}">TheInventory</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-white" href="{% url 'StartUp_Page1:homeP' %}">Dashboard <span
                                class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-white" href="{% url 'StartUp_Page1:Profile' %}">Admin Profile <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'StartUp_Page1:login' %}">Logout</a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
    <!--End Navbar-->

    <!--Topside-->
    <div class="container">
        <div class="row mt-4">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header bg-info text-white">
                        Information
                    </div>
                    <div class="card-body">
                            <h3 class="my-4">This is the Information</h3>
                        
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header bg-info text-white">
                        Statistics
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <a class="text-decoration-none text-dark" href="{% url 'StartUp_Page1:Staff' %}">
                                    <div class="card my-card shadow text-center p-3">
                                        <h4>Staff <i class="fas fa-users"></i></h4>
                                        <h3>4</h3>
                                    </div>
                                </a>
                            </div>
                            <div class="col-md-4">
                                <a class="text-decoration-none text-dark" href="{% url 'StartUp_Page1:Product' %}">
                                    <div class="card my-card shadow text-center p-3">
                                        <h4>Products <i class="fas fa-box"></i></h4>
                                        <h3>4</h3>
                                    </div>
                                </a>
                            </div>
                            <div class="col-md-4">
                                <a class="text-decoration-none text-dark" href="{% url 'StartUp_Page1:Orders' %}">
                                    <div class="card my-card shadow text-center p-3">
                                        <h4>Orders <i class="fas fa-shipping-fast"></i></h4>
                                        <h3>4</h3>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--End Topside-->


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
</body>

</html>

StartUp_Page/templates/Interfaces/product.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!--FontAwesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"
        integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">

    <!--Chartjs CDN-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>

    <!--Custome CSS-->
    <link rel="stylesheet" href="./style.css">

    <title>Product Page</title>
</head>

<body>

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-info bg-info">
        <div class="container">
            <a class="navbar-brand text-white" href="{% url 'StartUp_Page1:homeP' %}">TheInventory</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-white" href="{% url 'StartUp_Page1:homeP' %}">Dashboard <span
                                class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-white" href="{% url 'StartUp_Page1:Profile' %}">Admin Profile <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'StartUp_Page1:login' %}">Logout</a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
    <!--End Navbar-->

    <!--Topside-->
    <div class="container">
        <div class="row mt-4">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header bg-info text-white">
                        Information
                    </div>
                    <div class="card-body">
                            <h3 class="my-4">This is the Information</h3>
                        
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header bg-info text-white">
                        Statistics
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <a class="text-decoration-none text-dark" href="{% url 'StartUp_Page1:Staff' %}">
                                    <div class="card my-card shadow text-center p-3">
                                        <h4>Staff <i class="fas fa-users"></i></h4>
                                        <h3>0</h3>
                                    </div>
                                </a>
                            </div>
                            <div class="col-md-4">
                                <a class="text-decoration-none text-dark" href="{% url 'StartUp_Page1:Product' %}">
                                    <div class="card my-card shadow text-center p-3">
                                        <h4>Products <i class="fas fa-box"></i></h4>
                                        <h3>0</h3>
                                    </div>
                                </a>
                            </div>
                            <div class="col-md-4">
                                <a class="text-decoration-none text-dark" href="{% url 'StartUp_Page1:Orders' %}">
                                    <div class="card my-card shadow text-center p-3">
                                        <h4>Orders <i class="fas fa-shipping-fast"></i></h4>
                                        <h3>0</h3>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--End Topside-->

    <!--Table-->
    <div class="container">
        <div class="row my-4">
            <div class="col-md-4">
                <div class="border bg-white p-3">
                    <h4>Add Products</h4>
                    <hr>
                    <form method="POST">
                        {% csrf_token %}

                        {{ form }}
                        <input class="btn btn-success btn-block" type="submit" value="Add Product">

                    </form>
                </div>
            </div>
            <div class="col-md-8">
                <table class="table bg-white">
                    <thead class="bg-info">
                        <tr class="text-white">
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">Category</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Activity</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in items  %}
                        <tr>
                            <td> {{ i.name }} </td>
                            <td> {{ i.category }} </td>
                            <td> {{ i.quantity }} </td>
                            <td>
                                <a class="btn btn-info btn-sm" href="">Edit</a>
                                <a class="btn btn-danger btn-sm" href="{% url 'StartUp_Page1:DeleteP' i.id %}">Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>



    <!--End Table-->

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
</body>

</html>

StartUp_Page/templates/Interfaces/staff.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!--FontAwesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"
        integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">

    <!--Chartjs CDN-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>

    <!--Custome CSS-->
    <link rel="stylesheet" href="Interfaces/style.css">

    <title>Staff Page</title>
</head>

<body>

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-info bg-info">
        <div class="container">
            <a class="navbar-brand text-white" href="{% url 'StartUp_Page1:homeP' %}">TheInventory</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-white" href="{% url 'StartUp_Page1:homeP' %}">Dashboard <span
                                class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-white" href="{% url 'StartUp_Page1:Profile' %}">Admin Profile <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'StartUp_Page1:login' %}">Logout</a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
    <!--End Navbar-->

    <!--Topside-->
    <div class="container">
        <div class="row mt-4">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header bg-info text-white">
                        Information
                    </div>
                    <div class="card-body">
                            <h3 class="my-4">This is the Information</h3>
                        
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header bg-info text-white">
                        Statistics
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <a class="text-decoration-none text-dark" href="{% url 'StartUp_Page1:Staff' %}">
                                    <div class="card my-card shadow text-center p-3">
                                        <h4>Staff <i class="fas fa-users"></i></h4>
                                        <h3>0</h3>
                                    </div>
                                </a>
                            </div>
                            <div class="col-md-4">
                                <a class="text-decoration-none text-dark" href="{% url 'StartUp_Page1:Product' %}">
                                    <div class="card my-card shadow text-center p-3">
                                        <h4>Products <i class="fas fa-box"></i></h4>
                                        <h3>0</h3>
                                    </div>
                                </a>
                            </div>
                            <div class="col-md-4">
                                <a class="text-decoration-none text-dark" href="{% url 'StartUp_Page1:Orders' %}">
                                    <div class="card my-card shadow text-center p-3">
                                        <h4>Orders <i class="fas fa-shipping-fast"></i></h4>
                                        <h3>0</h3>

                                        <br>
                                        <h3>
                                            {{ name }}

                                        </h3>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--End Topside-->

    <!--Table-->
    <div class="container">
        <div class="row my-4">
            <div class="col-md-4"></div>
            <div class="col-md-8">
                <table class="table bg-white">
                    <thead class="bg-info">
                        <tr class="text-white">
                            <th scope="col">#</th>
                            <th scope="col">First</th>
                            <th scope="col">Last</th>
                            <th scope="col">Handle</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row"><a class="btn btn-info btn-sm" href="">View</a></th>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                        </tr>
                        <tr>
                            <th scope="row"><a class="btn btn-info btn-sm" href="">View</a></th>
                            <td>Jacob</td>
                            <td>Thornton</td>
                            <td>@fat</td>
                        </tr>
                        <tr>
                            <th scope="row"><a class="btn btn-info btn-sm" href="">View</a></th>
                            <td>Larry</td>
                            <td>the Bird</td>
                            <td>@twitter</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

    </div>



    <!--End Table-->

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
</body>

</html>

StartUp_Page/templates/StartUp_Page/HomePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logout Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }
        button {
            background-color: #ff4d4d;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }
        button:hover {
            background-color: #cc0000;
        }
    </style>
</head>
<body>

    <h1>Welcome User!</h1>
    
    <a href="{% url 'StartUp_Page1:logout1' %} " class="btn btn-primary"> LogOut</a>

</body>
</html>

StartUp_Page/templates/StartUp_Page/SigninPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }
        #footer {
                position: fixed;
                bottom: 0;
                left: 0;
                width: 100%;
                background-color: #f4f4f4;
                padding: 10px;
                text-align: center;
                color: #555;
            }
        h2 {
            text-align: center;
            margin-bottom: 20px;
            color:rgb(171, 23, 53);
            font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
    }

        form {
            background-color: #ffffff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
        }

        label {
            display: block;
            margin-bottom: 8px;
        }

        input {
            width: 100%;
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
        }

        button {
            background-color: #4caf50;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }

        .signup-link {
            text-align: center;
            margin-top: 16px;
        }
    </style>
</head>
<body style="background-color: #ecf1f0;">

    

<form action="{% url 'StartUp_Page1:login' %}" method="post" id="loginForm" >
    {% csrf_token %}
    <h2>Login</h2>
    <br>

    {{form}}

    <button type="submit">Login</button>

    <a href="{% url 'StartUp_Page1:sgnUp' %}" style="margin-left: 19px;"> Create a new account!!😀</a>
    

</form>





<div id="footer" style="text-align: center; margin-top: 40px; font-size: 16px; color: #000000; background-color:rgb(208, 233, 239)">
    Bilal Group of Companies. All rights reserved.
</div>

</body>
</html>
